export const doctorSpecializationOptions = [
  { value: "General Medicine", label: "General Medicine" },
  { value: "Family Medicine", label: "Family Medicine" },
  { value: "Internal Medicine", label: "Internal Medicine" },
  { value: "Pediatrics", label: "Pediatrics" },
  { value: "Cardiology", label: "Cardiology" },
  { value: "Dermatology", label: "Dermatology" },
  { value: "Emergency Medicine", label: "Emergency Medicine" },
  { value: "Endocrinology", label: "Endocrinology" },
  { value: "ENT", label: "ENT" },
  { value: "Gastroenterology", label: "Gastroenterology" },
  { value: "General Surgery", label: "General Surgery" },
  { value: "Neurology", label: "Neurology" },
  { value: "Nephrology", label: "Nephrology" },
  { value: "Obstetrics & Gynecology", label: "Obstetrics & Gynecology" },
  { value: "Oncology", label: "Oncology" },
  { value: "Ophthalmology", label: "Ophthalmology" },
  { value: "Orthopedic Surgery", label: "Orthopedic Surgery" },
  { value: "Psychiatry", label: "Psychiatry" },
  { value: "Pulmonology", label: "Pulmonology" },
  { value: "Radiology", label: "Radiology" },
  { value: "Urology", label: "Urology" },
] as const;
